# Generated by Django 4.2.19 on 2025-03-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_empdetails_emp_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetails',
            name='emp_city',
            field=models.CharField(max_length=25),
        ),
    ]
